modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="trueprimepiecetwo"
version="1.0.0"
displayName="trueprimepiecetwo"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Adon, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.trueprimepiecetwo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.trueprimepiecetwo]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trueprimepiecetwo]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trueprimepiecetwo]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trueprimepiecetwo]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trueprimepiecetwo]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration